export default [
  {
    role: "Frontend Engineer",
    company: "Gobi",
    companyLink: "https://www.gobi.rw/",
    location: "Remote,Kigali",
    start: "2025-01-01",
    done: [
      "Developed Gobi's platform using React, Next.js, and TypeScript",
      "Collaborated with the design team to implement user-friendly interfaces",
      "Conducted testing and debugging to ensure high-quality components",
    ],
    stack: ["next"],
  },
  {
    role: "Backend Engineer",
    company: "Eden Care Medical",
    companyLink: "https://www.edencaremedical.com/",
    location: "Remote, Kigali",
    start: "2024-10-07",
    done: [
      "Built backend systems with Spring boot and Java",
      "Developed REST APIs for core functionalities",
      "Integrated backend services with frontend applications",
    ],
    stack: ["java", "spring-boot"],
  },
  {
    role: "Frontend Engineer intern",
    company: "Eden Care Medical",
    companyLink: "https://www.edencaremedical.com/",
    location: "hybrid, Kigali",
    start: "2024-07-08",
    end: "2024-10-09",
    done: [
      "Built UI components library with React and TypeScript",
      "Implemented user interfaces with design team",
      "Conducted component testing and quality assurance",
    ],
    stack: [
      "react",
      "verdaccio",
      "storybook",
      "npm",
      "typescript",
      "github actions",
      "jira",
      "jest",
      "react testing library",
    ],
  },
  {
    role: "Technical Leadership program participant",
    company: "Andela",
    companyLink:
      "https://www.andela.com/blog-posts/andela-technical-leadership-program-investing-in-africas-tech-ecosystem-through-talent-development",
    location: "remote, Kigali",
    start: "2024-02-13",
    end: "2024-11-24",
    done: [
      "Developed full-stack apps with React and Node.js",
      "Collaborated in cross-functional team projects",
      "Participated in code reviews and technical mentorship",
    ],
    stack: [
      "node.js",
      "express.js",
      "typescript",
      "javascript",
      "react",
      "postgresql",
      "mongodb",
    ],
  },
  {
    role: "Digital Africa Program participant",
    company: "ICT Chamber & Digital africa",
    companyLink: "https://talent4startups.digital-africa.co/",
    location: "hybrid, Kigali",
    start: "2024-03-15",
    end: "2024-06-30",
    description: `
As a participant in the Digital Africa Program & ICT Chamber, I gained hands-on experience in mobile development using React Native. Through real-world projects, I built, tested, and deployed mobile apps, collaborating with diverse developers to refine my technical and problem-solving skills. The program emphasized innovation and practical application, enabling me to contribute to impactful projects.`,
    done: [
      "Built mobile apps with React Native",
      "Collaborated on cross-functional projects",
      "Participated in code reviews and workshops",
    ],
    stack: [
      "node.js",
      "express.js",
      "typescript",
      "javascript",
      "react native",
      "mongodb",
    ],
  },
];
